activation: elu
batch_size: 32
hidden_depth: 4
hidden_dim: 128
input_dim: 5
loss_bound_P_weight: 0.5
loss_bound_U_weight: 0.5
loss_bound_dUdy_weight: 0.5
loss_bound_k_weight: 0.7
loss_bound_stress_weight: 0.35
loss_phys_k_weight: 1.3
loss_phys_momentum_weight: 1.7
lr: 0.001
max_steps: 3600000
output_dim: 8
rho: 1.225
