activation: elu
batch_size: 32
hidden_depth: 4
hidden_dim: 128
input_dim: 5
loss_bound_P_weight: 0.1
loss_bound_U_weight: 0.1
loss_bound_dUdy_weight: 0.1
loss_bound_k_weight: 0.1
loss_bound_stress_weight: 0.1
loss_phys_k_weight: 10
loss_phys_momentum_weight: 10
lr: 0.0005
max_steps: 36000
output_dim: 8
rho: 1.225
